name: 3D Contrib

permissions:
  contents: write
  packages: write

on:
  schedule:
    - cron: 0 0 * * *
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: cnjimbo
      - name: Commit & Push
        run: |
          git config user.name cnjimbo
          git config user.email cnjimbo@dmsrs.org
          git add -A .
          git commit -m "generated"
          git push
